### ISSUE TITLE
[Bug]: structrues can not respawn in the server

### ISSUE THREAD

**Issue by Star-Jirachi** [someaddons/respawningstructures#3]
### Describe the bug you're experiencing

I use Respawning Structures mod in my forge server, but it can not respawn the structrues.
I use the command: /respawningstructures structureRespawnStatus <pos>, it says that structure's reset timer is over but the structure is not being reset.
After that I test in the single world, and it can respawn the same structures that I have test in my server.

### Reproducability

I use Respawning Structures mod in my forge server, but it can not respawn the structrues.
I use the command: /respawningstructures structureRespawnStatus <pos>, it says that structure's reset timer is over but the structure is not being reset.
After that I test in the single world, and it can respawn the same structures that I have test in my server.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

It doesn't have Exception Log

**Comment by someaddons** [comment]
Fixed in 3.0
