### ISSUE TITLE
[Bug]: villages respawn grass blocks and dirt paths incorrectly

### ISSUE THREAD

**Issue by AnyankaT** [someaddons/respawningstructures#5]
### Describe the bug you're experiencing

When a village respawns, it does a strange overlay of grass_blocks and dirt_paths - they end up replacing leaves in the trees and overlaying the existing blocks on paths.

### Reproducability

find a village - especially with trees.
respawn the village
see trees with grass blocks and dirt paths in the place of leaves.
![2024-07-31_12 58 38](https://github.com/user-attachments/assets/6374153d-c98f-457b-9b95-fe7ee361ed1b)
![2024-07-31_12 58 56](https://github.com/user-attachments/assets/01bf099e-ed1f-4049-871a-8493bc3ace8a)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/AnyankaT/3b66727e49db421edd52387c54d49936

**Comment by someaddons** [comment]
ye that can happen, thats simply how vanilla villages are coded to spawn. You just normally do not notice it because they spawn before trees

Maybe I can prevent path placement when respawning, hmm

**Comment by whydm2003724** [comment]
> ye that can happen, thats simply how vanilla villages are coded to spawn. You just normally do not notice it because they spawn before trees
> 
> Maybe I can prevent path placement when respawning, hmm

I have also encountered this problem before. Originally, I wanted to refresh a few more times and obtain more loot from the boxes. However, after a few refreshes, all the farmland and decorations near the farmland became as high as the mountains!
Hahaha, the mod is great, but I still hope you can solve this problem.

**Comment by someaddons** [comment]
Fixed in 3.0

**Comment by Infestidos** [comment]
This bug is back in Forge 1.20.1 v4.1
