### ISSUE TITLE
[Bug]: Structure Respawn not working on Minecraft Server

### ISSUE THREAD

**Issue by Aztrel** [someaddons/respawningstructures#6]
### Describe the bug you're experiencing

The counter gets to 0 minutes left and nothing happens 

### Reproducability

Just downloaded the most recent version and structure wont respawn

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Fabric

### Logs

No log exception

**Comment by govno1215** [comment]
i agree it's a big issue that i wish is adressed someday soon..

**Comment by someaddons** [comment]
Fixed in 3.0

**Comment by Aztrel** [comment]
Tysm!!
