### ISSUE TITLE
[Bug]: Automatic respawn does not work

### ISSUE THREAD

**Issue by Looodon** [someaddons/respawningstructures#8]
### Describe the bug you're experiencing

If you set "minutesUntilRespawn": any number (like 2 or above) it just doesn't work on both solo/multiplayer. I've tested it for hours, i really hope you look into it. This mod so is a game changer & important so I hope its looked into

### This will also help:

Please add a config to allow structures to respawn even if players are living, no matter how much they built stuff or portals are residing inside. Some structures are boss lairs & would need to be respawned regardless of blocks placed/portals

### Reproducability

1) Create new modpack, add the mod
2) Launch the game, generate the config, close the game
3) set "minutesUntilRespawn": to any number 2 or above
4) break a structure (mansion for example) and wait

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://pastebin.com/hf48MmSG

**Comment by someaddons** [comment]
Fixed in 3.0
